03-objects-arrays-intro-to-testing
js-tasks-ru/js-20200928_aleksey54 pull request #4
Opened 2020-10-07 18:54 UTC by alekseiovechkin

2020-10-07 19:01 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — изменен
```

2020-10-07 19:07 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    return path.split('.').reduce(function (object, value) {
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2020-10-07 19:08 UTC, dosandk commented on package.json
> +    "jest-fetch-mock": "^3.0.3",
нельзя изменять системные файлы. Пожалуйста удалить данное изменение из PR

2020-10-07 19:08 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
>  export function trimSymbols(string, size) {
решение принимается

2020-10-07 19:09 UTC, dosandk requested changes
решения кроме createGetter принимаются

2020-10-08 06:30 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — изменен
```

2020-10-08 06:37 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — удален
```

2020-10-08 07:03 UTC, closed without merging